### ISSUE TITLE
Not working on meteor/devel branch

### ISSUE THREAD

**Issue by Igor1201** [raix/stubfence#2]

**Comment by raix** [comment]
any error messages?

**Comment by Igor1201** [comment]
Wow, I was pretty sure I had edited this issue weeks ago. I'm really sorry about that.
Well, stubfence crashed with `ground:db` and meteor devel branch (meteor/meteor@ed43873fb0d9ddfca09530888cb621e2c714ae27).

```
W20150802-00:29:12.413(-3)? (STDERR) /Users/igor/Desktop/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150802-00:29:12.413(-3)? (STDERR)            				throw(ex);
W20150802-00:29:12.413(-3)? (STDERR)            				      ^
W20150802-00:29:12.413(-3)? (STDERR) Error: Arg! Meteor just broke raix:stubfence! Please report to @raix at github, and he will work his butt off trying to fix this
W20150802-00:29:12.414(-3)? (STDERR)     at inFence (raix:stubfence/util.js:4:1)
W20150802-00:29:12.414(-3)? (STDERR)     at /Users/igor/Projects/stubfencetest/project/.meteor/local/build/programs/server/packages/raix_stubfence.js:27:4
W20150802-00:29:12.414(-3)? (STDERR)     at /Users/igor/Projects/stubfencetest/project/.meteor/local/build/programs/server/packages/raix_stubfence.js:124:3
W20150802-00:29:12.414(-3)? (STDERR)     at /Users/igor/Projects/stubfencetest/project/.meteor/local/build/programs/server/boot.js:222:10
W20150802-00:29:12.414(-3)? (STDERR)     at Array.forEach (native)
W20150802-00:29:12.414(-3)? (STDERR)     at Function._.each._.forEach (/Users/igor/Desktop/meteor/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150802-00:29:12.414(-3)? (STDERR)     at /Users/igor/Projects/stubfencetest/project/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

I don't think I have any better error description.

**Comment by raix** [comment]
Got it - Meteor must have changed the api
